### ISSUE TITLE
Q: Which Java version(s) do we support?

### ISSUE THREAD

**Issue by connollyst** [numenta/htm.java#143]
In the ``pom.xml`` we specify source & target Java versions of ``1.7``; likewise in ``build.gradle``. 

However, I see we aren't using ``1.7`` niceties such as 'diamonds', e.g.:
``Map<Integer, String> map = new HashMap<>``

Can I feel free to code against Java 7 or do we want to support Java 6 also? If the latter, I'll put in a ticket to update the ``pom.xml`` and ``build.gradle``.

**Comment by connollyst** [comment]
Also, would Java 8 be on the table?

**Comment by connollyst** [comment]
Update, I see _we are_ using Java 7 Diamonds in some places. Because of this, ``htm.java`` couldn't be compiled with Java 6, even if the ``pom.xml`` were modified.

I think this is fine, but suggest we use Diamonds where ever possible to keep the code clean & consistent.

**Comment by cogmission** [comment]
Hi Sean,
Yes, just recently code was merged that used the "diamonds" ascribing to JDK 7 syntax. I don't however view the non use of it as "unclean" it is just a more recent convention. At the present time, Java 7 is the lower bound on the versions. Very soon however, because htm.java is relatively new development I would like to migrate the the minimum version to Java 8. This requires an update of the build.gradle (and therefore the pom.xml file - though this is *not* a Maven project), and also testing of the Travis continuous integration functionality too. This might be a great task for a new comer and if you would like to open an "issue" to document this task, that would good. This way a beginner could get their feet wet with htm.java. It could be worded something like this: "Htm.java would benefit from a global reformatting of generics to use the "diamond" ("<>") style syntax to shorten verbosity."

**Comment by connollyst** [comment]
Very good, thanks for clarifying.

I'll put in a ticket and might well pick it up if there's no other low hanging fruit to orient myself with.

Regarding Gradle & Maven, why do we have a ``pom.xml`` if it's not a Maven project? (We can move to another 'issue' if this is a bigger topic)

**Comment by cogmission** [comment]
The use of Travis CI (used by Numenta) as the continuous integration server, coupled with the universal use of "Coveralls" as the code coverage reporting tool mandates the use of a Maven plugin for its integration into our build process. The only known way (at the time of the build creation) to use coveralls was to use the one and only Maven plugin developed for this task (See here: https://github.com/trautonen/coveralls-maven-plugin). I absolutely abhor Maven and it irritates me to no end that it is required for the build. (I don't mind providing a pom and maven adherence for those who like Maven though - I just don't like the fact that its use is imposed. So for now, we live with it :)

**Comment by connollyst** [comment]
Got it, cheers.

**Comment by rhyolight** [comment]
Guys, if you want to get rid of Coveralls in order to remove the Maven dependency, that is cool with me. I would like to see another code coverage tool put into place if possible, though.

**Comment by cogmission** [comment]
I never even thought to ask! This is why a community of developers is much
better than one. :)

Ok, we'll look into it because I do believe it is worth removing Maven as a
mandated tool.

Thanks!
David

On Sat, Jan 17, 2015 at 2:34 PM, Matthew Taylor <notifications@github.com>
wrote:

> Guys, if you want to get rid of Coveralls in order to remove the Maven
> dependency, that is cool with me. I would like to see another code coverage
> tool put into place if possible, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/143#issuecomment-70383181>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by solovyevk** [comment]
I have more experience with Maven and manage this project with it.
I'd like Maven to stay very much.

Thank You,

Kirill.

**Comment by cogmission** [comment]
As long as one has a pom file, they can use Maven for dependency management
right? I don't propose that we remove the pom file, and ignore its upkeep,
I just don't think it should be invoked by Travis CI thus making it so that
the project cannot be managed without it. Does that sound right/fair?

David

On Sat, Jan 17, 2015 at 6:22 PM, Kirill <notifications@github.com> wrote:

> I have more experience with Maven and manage this project with it.
> I'd like Maven to stay very much.
>
> Thank You,
>
> Kirill.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/143#issuecomment-70390890>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by solovyevk** [comment]
Got it, I'm fine with removing maven calls from travis CI build.

**Comment by connollyst** [comment]
An afterthought on Java 8: Android doesn't support Java 8 so maybe we should stick with Java 7 for now?
