### ISSUE TITLE
Reevaluate build system & dependency management

### ISSUE THREAD

**Issue by connollyst** [numenta/htm.java#147]
Stems from conversation in #143 :

@cogmission 
> The use of Travis CI (used by Numenta) as the continuous integration server, coupled with the universal use of "Coveralls" as the code coverage reporting tool mandates the use of a Maven plugin for its integration into our build process.

@rhyolight 
> If you want to get rid of Coveralls in order to remove the Maven dependency, that is cool with me. I would like to see another code coverage tool put into place if possible, though.

This issue is to reconsider options for building the project & managing dependencies. A resolution should  build on Travis CI and generate code coverage statistics for tests.

**Comment by connollyst** [comment]
Note: There was talk in #143 of using Gradle on Travis CI but keeping Maven for developer use. I personally favor consolidating to a single build & dependency management tool, it keeps things simpler and cleaner. @solovyevk, you mentioned Maven is your tool of preference, can you comment on why you would favor it over Gradle?

-Sean

**Comment by cogmission** [comment]
Sean,

Gradle is the dependency management tool we are aiming for going forward.
It is the tool used by the Oracle development staff for Java and by
OpenJDK. It uses an actual programming language (not complex-ml) and is
much more configurable and can accomplish more in a clearer way. It doesn't
preclude the use of Maven, (those who prefer Maven can still use it locally
because Gradle observes the conventions that Maven depends on; can use the
Maven Central repository; and it can invoke Maven for those who choose that
too).

Because this isn't an exclusive decision (Maven doesn't have to be out of
the picture for those who like it), I'm putting my foot down on this one,
sorry :)

Thanks,
David

On Sun, Jan 18, 2015 at 3:13 AM, Sean Connolly <notifications@github.com>
wrote:

> Note: There was talk in #143
> <https://github.com/numenta/htm.java/issues/143> of using Gradle on
> Travis CI but keeping Maven for developer use. I personally favor
> consolidating to a single build & dependency management tool, it keeps
> things simpler and cleaner. @solovyevk <https://github.com/solovyevk>,
> you mentioned Maven is your tool of preference, can you comment on why you
> would favor it over Gradle?
>
> -Sean
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/147#issuecomment-70401346>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by connollyst** [comment]
No problem, just wanted to clarify it here rather than let #143 go off topic.

Why not get rid of Maven? Gradle is perfectly standard & capable, so settling on that and removing the ``pom.xml`` keeps things cleaner, more consistent, and easier to maintain.

**Comment by cogmission** [comment]
>
> Why not get rid of Maven? Gradle is perfectly standard & capable, so
> settling on that and removing the pom.xml keeps things cleaner, more
> consistent, and easier to maintain.


Even the OpenJDK dev staff wish they could provide a pom.xml file for their
project because it broadens accessibility to the code.  The idea is to
widen the audience for htm.java as much as possible, it is the "Prime
Directive" and its reason for being (because we want more people to get
involved with NuPIC in general) :)

Java is the most popular programming language in use today which is why
htm.java exists and is why I've always felt there should be a Java offering
and why Matt and the development staff at Numenta, have been so supportive
of its development. By having a Java version of NuPIC we can hopefully
introduce HTM technology to a broader audience and accelerate its growth.

David



On Sun, Jan 18, 2015 at 7:01 AM, Sean Connolly <notifications@github.com>
wrote:

> No problem, just wanted to clarify it here rather than let #143
> <https://github.com/numenta/htm.java/issues/143> go off topic.
>
> Why not get rid of Maven? Gradle is perfectly standard & capable, so
> settling on that and removing the pom.xml keeps things cleaner, more
> consistent, and easier to maintain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/147#issuecomment-70407473>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by connollyst** [comment]
Got it.
Thanks David.
