### ISSUE TITLE
Missing jar

### ISSUE THREAD

**Issue by chessweb01** [numenta/htm.java#178]
I did a 'git pull origin master' on my local copy and noticed that now the SLF4J jar is missing. Adding slf4j-api-1.7.10.jar fixed it.

**Comment by cogmission** [comment]
@chessweb01

Thank you. As it turns out, I was just working on the addition of this due
to yesterday's merge of the slf4j capability. For convenience we have tried
to include all needed dependencies in the "libs" directory (for those who
prefer not to use a repository management library such as Gradle or Maven).
Officially, the project is built using Gradle but supports both Gradle and
Maven. I will update the "libs" directory today with the required
dependencies.

Thanks again for getting involved!

David

On Thu, Feb 5, 2015 at 7:55 AM, chessweb01 <notifications@github.com> wrote:

> I did a 'git pull origin master' on my local copy and noticed that now the
> SLF4J jar is missing. Adding slf4j-api-1.7.10.jar fixed it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/178>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by cogmission** [comment]
Fixed
