### ISSUE TITLE
MAKE IT OFFICIAL!

### ISSUE THREAD

**Issue by rhyolight** [numenta/htm.java#193]
![803os](https://cloud.githubusercontent.com/assets/15566/6355957/d98c0fc0-bc0e-11e4-9132-f8bcf9df1b26.jpeg)

**Comment by cogmission** [comment]
:clap:

**Comment by anubhavchaturvedi** [comment]
Congratulations :)

**Comment by cogmission** [comment]
To YOU too!  Thanks for helping make this a possibility, Anubhav!

On Wed, Feb 25, 2015 at 8:20 AM, Anubhav Chaturvedi <
notifications@github.com> wrote:

> Congratulations :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/193#issuecomment-75966844>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by cogmission** [comment]
Don't forget to participate in the Network API Architecture discussion -->
http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/2015-February/003236.html

On Wed, Feb 25, 2015 at 8:40 AM, cogmission <cognitionmission@gmail.com>
wrote:

> To YOU too!  Thanks for helping make this a possibility, Anubhav!
>
> On Wed, Feb 25, 2015 at 8:20 AM, Anubhav Chaturvedi <
> notifications@github.com> wrote:
>
>> Congratulations :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/numenta/htm.java/issues/193#issuecomment-75966844>.
>>
>
>
>
> --
> *We find it hard to hear what another is saying because of how loudly "who
> one is", speaks...*
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by sambitgaan** [comment]
Hi,

I had gone through all the 4 points and I like the idea very much specially
point number 1 and 3.
I would like to participate in the discussion.

Regards,
Sambit Gaan

**Comment by cogmission** [comment]
The "discussion" is open. There isn't going to be an "event" or special
time to contribute. If anyone has ideas or specific points they would like
to make or  things they would like to see included, maybe - then simply
comment to the discussion here:
http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/2015-February/003236.html

On Wed, Feb 25, 2015 at 10:17 AM, sambitgaan <notifications@github.com>
wrote:

> Hi,
>
> I had gone through all the 4 points and I like the idea very much specially
> point number 1 and 3.
> I would like to participate in the discussion.
>
> Regards,
> Sambit Gaan
>
>
> On Wed, Feb 25, 2015 at 8:14 PM, David Ray <notifications@github.com>
> wrote:
>
> > Don't forget to participate in the Network API Architecture discussion
> -->
> >
> >
> http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/2015-February/003236.html
> >
> > On Wed, Feb 25, 2015 at 8:40 AM, cogmission <cognitionmission@gmail.com>
> > wrote:
> >
> > > To YOU too! Thanks for helping make this a possibility, Anubhav!
> > >
> > > On Wed, Feb 25, 2015 at 8:20 AM, Anubhav Chaturvedi <
> > > notifications@github.com> wrote:
> > >
> > >> Congratulations :)
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/numenta/htm.java/issues/193#issuecomment-75966844
> >.
> > >>
> > >
> > >
> > >
> > > --
> > > *We find it hard to hear what another is saying because of how loudly
> > "who
> > > one is", speaks...*
> > >
> >
> >
> >
> > --
> > *We find it hard to hear what another is saying because of how loudly
> "who
> > one is", speaks...*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/numenta/htm.java/issues/193#issuecomment-75971363>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/issues/193#issuecomment-75990186>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*
