### ISSUE TITLE
simple install instructions

### ISSUE THREAD

**Issue by breznak** [numenta/htm.java#299]
the Readme feels a bit cluttered, I'd welcome a simple `INSTALL.txt` with instructions.

**Comment by cogmission** [comment]
@breznak Issues aren't a personal communication mechanism, we can discuss this on gitter or the "hacker's" mailing list...

**Comment by breznak** [comment]
Well, this is a proposal for feature-enhancement/documentation, close as you see fit.

**Comment by cogmission** [comment]
Why not propose this in "hackers"? Also, Java projects don't have to be "installed" - you just link against them, providing their name and location. Developer environments are a different mode of use - as stated elsewhere; I can only provide assistance with Eclipse at this point - but dev environment support is a slippery slope.

**Comment by cogmission** [comment]
On second thought, seeing this as a proposal for "feature enhancement" does make this appropriate to put here. However, I'm still hesitant to start supporting multiple dev environments. If you want to then support user Net Beans problems, then I'd agree to a wiki location for NB help like the one we have for Eclipse. 

I went through this with Maven which I swore I would never support. But since we offer a pom.xml file and we use the Maven Central repo, users feel as if the project should remain viable as a maven build target (which I have no interest in because I abhor maven, and is why I use Gradle). Now I get inquiries for maven problems which I don't feel right saying, "tough luck, figure it out yourself or use a proper build mechanism" - which is what I would like to say... :-P

**Comment by breznak** [comment]
Just to clarify, I didn't want any specific instructions (and this is definitely not about netbeans)...I'm used to `git clone`, read Readme/Install.txt and be done with it :) So I was suggesting: 

```
=====INSTALL=====
Dependencies: 
java >= 1.8
gradle >= 1.7

Install:
git clone https://github.com/numenta/htm.java
cd htm.java
gradle check
```

**Comment by cogmission** [comment]
@breznak  Ok, do you want to submit this Install.txt file to the main repo dir? and put up a PR?
