### ISSUE TITLE
Unable to use FieldMetaType COORD results in IllegalStateException

### ISSUE THREAD

**Issue by DennisRutjes** [numenta/htm.java#371]

**Comment by DennisRutjes** [comment]
the geospatialencoder en coordinate encoder are handled equally in class FieldMetaType :
 case COORD :
            case GEO :  {
            	String[] parts = input.split("[\\s]*\\;[\\s]*");
            	return (T)new Tuple(Double.parseDouble(parts[0]), Double.parseDouble(parts[1]), Double.parseDouble(parts[2]));
            } 

this results in an IllegalStateException, Coord can be of dimension N en is of type int. the last entry should be regarded as a radius.

**Comment by cogmission** [comment]
Thanks @DennisRutjes! We'll post a fix soon!

**Comment by cogmission** [comment]
This is simple to fix. The above code takes 2 coordinates for both type COORD and GEO (indicating use with the CoordinateEncoder and GeospatialCoordinateEncoder, respectively), **however** the GEO takes an additional input of "radius" making 3 inputs that it handles as opposed to two for the regular COORD. This breaks the COORD field parsing because they are no longer equal (whereas at one time they were mistakenly treated equally here). 

The COORD case should be isolated and do exactly what the GEO case does except only work with 2 arguments instead of 3. Easy peasy! (Then of course, a test in the Network package should be written to show that both cases work).

**Comment by DennisRutjes** [comment]
Not entirely true ;-) COORD should use a N-dimensional integer coordinate space + 1 RADIUS 

http://numenta.org/docs/nupic/classnupic_1_1encoders_1_1coordinate_1_1_coordinate_encoder.html

**Comment by cogmission** [comment]
Nupic's CoordinateEncoder ([coordinate.py](https://github.com/numenta/nupic/blob/master/src/nupic/encoders/coordinate.py)) is only tested with 2 coordinates; while I do see that the function (both the python version and the Java version), seems to be able to handle n-dimensions; the test [seen here](https://github.com/numenta/nupic/blob/master/tests/unit/nupic/encoders/coordinate_test.py) only tests 2 dimensions - (which for me is the same as not existing). So that's why I say that it only handles two dimensions.

The NAPI by design, simplifies the parameter expectations by generalizing to the most commonly used form of the underlying algorithms (just as the Python NAPI, and then even more so the Python OPF, does) to simplify and streamline usage.

Nevertheless, we can define the input handled by the FieldMetaType as having n-dimensions as you say because the underlying code already handles it.

Therefore, the line [here](https://github.com/numenta/htm.java/blob/master/src/main/java/org/numenta/nupic/FieldMetaType.java#L100) should return a Tuple consisting of however many dimensions stated, with the last one understood to be the radius. Something like...

``` Java
String[] parts = /* PATTERN FOR SPLITTING ARBITRARY NUMBER ARGS SEP'D BY ";" */
int[] convertedParts = convert(parts); // convert to integer array; the last integer should be the radius.
return (T)new Tuple(convertedParts);
```
